adding XML and modifying CSV parsers
ardium-pl/ergis-accounting-app pull request #91
Opened 2024-06-11 17:12 UTC by lolocob7

2024-06-17 16:49 UTC, joker876 requested changes

2024-06-17 16:49 UTC, joker876 commented on client/src/app/services/faktoring/faktoring.service.ts
> +                console.log(csvObjects);
console.log do usunięcia

2024-06-17 16:49 UTC, joker876 commented on client/src/app/services/jpk/jpk.service.ts
> +      console.log('Parsed XML:', result);
do usunięcia

2024-06-17 16:49 UTC, joker876 commented on client/src/app/services/jpk/jpk.service.ts
> +        console.log(csvObjects);
console.log do usunięcia

2024-06-18 10:22 UTC, Pawel-Bakalarz approved these changes

2024-06-18 10:22 UTC, Pawel-Bakalarz approved these changes

2024-06-18 10:23 UTC, merged